### ISSUE TITLE
Strip leading/trailing whitespace from text fields

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#159]
## Description
Strip leading/trailing whitespace from text fields on save. Do this at the model level.

* group name
* group description
* landscape name
* landscape description
* user family name
* user given name

**Comment by cacarrara** [comment]
An approach for dealing with it would be:
- Override models' `clean()` method
- Call `self.[text_field].strip()` inside the clean

The `clean()` method is already being called on API level because the API calls the model's `full_clean()` method:

https://github.com/techmatters/terraso-backend/blob/9131ca779ac51fccfe4bc38f42cb06ccddfcf4e2/terraso_backend/apps/graphql/schema/commons.py#L50
